apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: custom-config
spec:
  # namespace: chainsaw
  timeouts:
    apply: 120s
    assert: 120s
    cleanup: 120s
    delete: 120s
    error: 10s
    exec: 45s
  # skipDelete: true
  failFast: true
