apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: custom-config
spec:
  # namespace: chainsaw
  timeouts:
    apply: 300s
    assert: 420s
    cleanup: 120s
    delete: 120s
    error: 10s
    exec: 120s
  # skipDelete: true
  failFast: true
  parallel: 1
