# permissions for end users to edit trinocatalogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: trinocatalog-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: trino-operator
    app.kubernetes.io/part-of: trino-operator
    app.kubernetes.io/managed-by: kustomize
  name: trinocatalog-editor-role
rules:
- apiGroups:
  - trino.zncdata.dev
  resources:
  - trinocatalogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trino.zncdata.dev
  resources:
  - trinocatalogs/status
  verbs:
  - get
