apiVersion: trino.zncdata.dev/v1alpha1
kind: TrinoCluster
metadata:
  labels:
    app.kubernetes.io/name: trinocluster
    app.kubernetes.io/instance: trinocluster-sample
    app.kubernetes.io/part-of: trino-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: trino-operator
  name: trinocluster-sample
spec:
  coordinators:
    roleGroups:
      default:
        replicas: 1
  workers:
    roleGroups:
      default:
        replicas: 1
